import { Medicine } from "src/Models/Medicine/Entities/medicine.entity";
import { ITreatment } from "../Interfaces/treatment.interface";
import { Entity } from "typeorm";
import { TABLE_NAMES } from "src/Utils/constants";
import { UserSymptom } from "src/Models/Treatable/Entities/usersymptom.entity";
import { Profile } from "src/Models/Users/Entities/profile.entity";
import { Illness } from "src/Models/Treatable/Entities/illness.entity";

//@Entity({name: TABLE_NAMES.TREATMENT})
export class Treatment implements ITreatment{
    medicineDosage: number;//
    medicines: Medicine[];// somehow generated by algorithm 
    administrationRecommendations: string;//
    userSymptoms: UserSymptom[];
    userIllnesses: Illness[];
    userProfile: Profile;

}